source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SantiIgualABradPitt_Tests', :exclusive => true do
  pod "SantiIgualABradPitt", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
